#!/usr/bin/env python3
"""
Dev server that refuses to let the browser cache anything -- and that speaks
enough HTTP to serve media.

Two bugs live here, both of which cost real time before they were understood,
and both of which look exactly like "my code does not work":

1. `python3 -m http.server` sends Last-Modified and honours If-Modified-Since,
   so a regenerated PNG keeps being served from cache as a 304 and the page
   shows the old art. Almost every asset here is regenerated by a tool rather
   than edited by hand, so nothing in `assets/` should ever be cached in dev.

2. `SimpleHTTPRequestHandler` ignores the Range header and answers with a 200
   and the entire file. `fetch()` does not care, so the network looks healthy.
   An <audio> or <video> element very much does care: Chrome's media stack asks
   for a byte range, gets a 200, and stalls at readyState 0 forever with no
   error event -- silently, which is the worst way for it to fail. Safari
   refuses outright.

So: no caching for the generated art, real 206 responses for everything, and an
exemption for audio -- a 3MB soundtrack is not regenerated by any tool here, and
re-downloading it on every reload is pure cost.

Usage:  python3 tools/serve.py [port]
"""
import io
import os
import re
import sys
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

RANGE = re.compile(r"^bytes=(\d*)-(\d*)$")

# Extensions that are hand-supplied rather than tool-generated, and are large.
CACHEABLE = (".mp3", ".ogg", ".wav", ".m4a", ".woff2")


class Dev(SimpleHTTPRequestHandler):
    # Ranges and keep-alive both behave better under 1.1, and the base class
    # sets an accurate Content-Length on every response, which 1.1 requires.
    protocol_version = "HTTP/1.1"

    def end_headers(self):
        self.send_header("Accept-Ranges", "bytes")
        if not self.path.lower().endswith(CACHEABLE):
            self.send_header("Cache-Control", "no-store, must-revalidate")
            self.send_header("Pragma", "no-cache")
            self.send_header("Expires", "0")
        super().end_headers()

    def send_header(self, key, value):
        # Suppress the validators the browser would otherwise use to re-use a
        # stale copy; no-store alone is not always enough in practice. Media is
        # exempt -- there we *want* the browser to revalidate and re-use.
        if key.lower() in ("last-modified", "etag") \
                and not self.path.lower().endswith(CACHEABLE):
            return
        super().send_header(key, value)

    def send_head(self):
        """Serve a 206 when a byte range was asked for; otherwise as normal."""
        header = self.headers.get("Range")
        if not header:
            return super().send_head()

        path = self.translate_path(self.path)
        if os.path.isdir(path):
            return super().send_head()
        try:
            with open(path, "rb") as f:
                size = os.fstat(f.fileno()).st_size
                m = RANGE.match(header.strip())
                if not m:
                    self.send_error(400, "Malformed Range")
                    return None
                first, last = m.groups()
                if first == "":
                    # "bytes=-N": the final N bytes.
                    if last == "":
                        self.send_error(400, "Malformed Range")
                        return None
                    start, end = max(0, size - int(last)), size - 1
                else:
                    start = int(first)
                    end = int(last) if last else size - 1
                end = min(end, size - 1)

                if start >= size or start > end:
                    self.send_response(416)
                    self.send_header("Content-Range", f"bytes */{size}")
                    self.send_header("Content-Length", "0")
                    self.end_headers()
                    return None

                f.seek(start)
                chunk = f.read(end - start + 1)
        except OSError:
            self.send_error(404, "File not found")
            return None

        self.send_response(206)
        self.send_header("Content-Type", self.guess_type(path))
        self.send_header("Content-Range", f"bytes {start}-{end}/{size}")
        self.send_header("Content-Length", str(len(chunk)))
        self.end_headers()
        return io.BytesIO(chunk)

    def log_message(self, fmt, *args):
        pass                                   # quiet; the tools do the talking


def main():
    port = int(sys.argv[1]) if len(sys.argv) > 1 else 5174
    os.chdir(ROOT)
    print(f"spiderman on http://localhost:{port}  (no cache, ranges enabled)")
    ThreadingHTTPServer(("", port), Dev).serve_forever()


if __name__ == "__main__":
    main()
